matrix:
- name: Python
  sources:
  - '**/*.py'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .spellcheck/wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.python:
      comments: true
      docstrings: true
      group_comments: false
      decode_escapes: true
      strings: false    