name: Lint
on:
  pull_request:
  push:
    branches:
      - main
  # schedule:
  #   # Run every week at 20:00 on Sunday
  #   - cron: "0 20 * * 0"

jobs:
  ament_lint:
    name: "${{ matrix.package-name }} : ${{ matrix.linter }}"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
          # linter: [cppcheck, cpplint, uncrustify, flake8, pep257, lint_cmake, xmllint, copyright]
          linter: [flake8, pep257, xmllint, copyright]
          package-name:
          - ci_test
          #- ...
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.package-name }}-${{ matrix.linter }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.7
    - run: sudo pip install pydocstyle==6.1.1 # downgrade to fix https://github.com/ament/ament_lint/pull/428
    - uses: ros-tooling/action-ros-lint@0.1.3
      with:
        linter: ${{ matrix.linter }}
        package-name: ${{ matrix.package-name }}
