name: Spellcheck Action
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.33.1
      name: Spellcheck
      with:
        config_path: .spellcheck/spellcheck_config.yml
        task_name: Python
